---
- name: configuring Jenkins Software
  hosts: jenkinsserver
  tasks:
    - name: installing required softwares
      apt:
       name: "{{item.a}}"
       state: "{{item.b}}"
       update_cache: "{{item.c}}"
      with_items:
        - {a: openjdk-11-jdk,b: present,c: yes}
        - {a: git,b: present,c: no} 
        - {a: maven,b: present,c: no}
    - name: downloading jenkins.war file
      get_url:
       url: https://get.jenkins.io/war-stable/2.440.1/jenkins.war
       dest: /home/ubuntu

- name: Configuring Tocmcat9 and admin
  hosts: server
  tasks: 
    - name: installing tomcat9 and admin
      apt:
       name: "{{item.a}}"
       state: "{{item.b}}"
       update_cache: "{{item.c}}"
      with_items:
       - {a: tomcat9,b: present,c: yes} 
       - {a: tomcat9-admin,b: present,c: no}
    - name: copying and modifying tomcat-users.xml file
      copy:
       src: tomcat-users.xml
       dest: /etc/tomcat9
      notify: Restart tomcat9

  handlers:
    - name: Restart tomcat9
      service: 
       name: tomcat9
       state: restarted  
...
